### PR TITLE
Provide more visual cues that the keys are about to change

### PR DESCRIPTION
**Pull request by jhriggs**
Make accounts dark red and pulsing when <= 10 seconds remaining (similar to Authenticator app).

### CODE REVIEW

**Comment by gbraad** [comment]
Will check this code ASAP. Just returned from a holiday.

**Comment by jhriggs** [comment]
I moved the color to a '#accounts .expiring' to move the color to CSS. That's a better place for it. The fade/pulse, though, has to be in the code, because it is using jQuery's fadeTo(). I don't think there is any way to do the fading outside JS, is there?

**Comment by gbraad** [comment]
fadeto is possible using CSS with keyframes

**Comment by davchana** [comment]
Does Google Auth app pulsate when less than 10 seconds? It will not be a good sight for eyes, & if you add, please make it optional in settings. Thanks

**Comment by gbraad** [comment]
I agree. The styling is too much.
It would be preferred to have the countdown pulsate instead.

**Pull request closed without merging**
